
#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - "3.5"

services: postgresql

before_install:
  - export PYTHONPATH=$HOME/builds/henriquefacioli/gd-ae-
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r dependencies.txt
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - "sh run_script.sh travis"
